version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
      commit-message:
          prefix: chore
          prefix-development: chore
          include: scope
      ignore:
          - dependency-name: zod
            update-types: ["version-update:semver-major"]
            versions: [">=4.0.0"]
