name: ci
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    test:
        name: test (node ${{ matrix.node-version }})
        permissions:
            contents: read
        runs-on: macos-latest
        strategy:
            matrix:
                node-version: ['22.x', '24.x', '26.x']
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm

            - run: npm ci
            - run: npm run lint:eslint
            - run: npm run lint:prettier
            - name: Build & Test
              run: npm test

    commitlint:
        permissions:
            contents: read
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: '22.x'
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Print versions
              run: |
                  git --version
                  node --version
                  npm --version
                  ./node_modules/.bin/commitlint --version

            - name: Validate current commit (last commit) with commitlint
              if: github.event_name == 'push'
              run: ./node_modules/.bin/commitlint --last --verbose

            - name: Validate PR commits with commitlint
              if: github.event_name == 'pull_request'
              run: ./node_modules/.bin/commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
