name: release
on:
    push:
        branches:
            - develop
jobs:
    release:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  persist-credentials: true

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '25'

            - name: Install dependencies
              run: npm install

            - name: Lint with ESLint
              run: npm run lint:eslint

            - name: Lint with Prettier
              run: npm run lint:prettier

            - name: Build
              run: npm run build

            - name: Semantic Release
              run: npx semantic-release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
